// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/user_finder/user_finder.proto

package user_finder_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByEmailRequest) Reset() {
	*x = FindByEmailRequest{}
	mi := &file_proto_user_finder_user_finder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByEmailRequest) ProtoMessage() {}

func (x *FindByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_finder_user_finder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByEmailRequest.ProtoReflect.Descriptor instead.
func (*FindByEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_finder_user_finder_proto_rawDescGZIP(), []int{0}
}

func (x *FindByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SaveUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserRequest) Reset() {
	*x = SaveUserRequest{}
	mi := &file_proto_user_finder_user_finder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserRequest) ProtoMessage() {}

func (x *SaveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_finder_user_finder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserRequest.ProtoReflect.Descriptor instead.
func (*SaveUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_finder_user_finder_proto_rawDescGZIP(), []int{1}
}

func (x *SaveUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_proto_user_finder_user_finder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_finder_user_finder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_finder_user_finder_proto_rawDescGZIP(), []int{2}
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SaveUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserResponse) Reset() {
	*x = SaveUserResponse{}
	mi := &file_proto_user_finder_user_finder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserResponse) ProtoMessage() {}

func (x *SaveUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_finder_user_finder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserResponse.ProtoReflect.Descriptor instead.
func (*SaveUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_finder_user_finder_proto_rawDescGZIP(), []int{3}
}

func (x *SaveUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	SlackName     string                 `protobuf:"bytes,3,opt,name=slack_name,json=slackName,proto3" json:"slack_name,omitempty"`
	SlackId       string                 `protobuf:"bytes,4,opt,name=slack_id,json=slackId,proto3" json:"slack_id,omitempty"`
	GithubLogin   string                 `protobuf:"bytes,5,opt,name=github_login,json=githubLogin,proto3" json:"github_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_user_finder_user_finder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_finder_user_finder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_user_finder_user_finder_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetSlackName() string {
	if x != nil {
		return x.SlackName
	}
	return ""
}

func (x *User) GetSlackId() string {
	if x != nil {
		return x.SlackId
	}
	return ""
}

func (x *User) GetGithubLogin() string {
	if x != nil {
		return x.GithubLogin
	}
	return ""
}

var File_proto_user_finder_user_finder_proto protoreflect.FileDescriptor

const file_proto_user_finder_user_finder_proto_rawDesc = "" +
	"\n" +
	"#proto/user_finder/user_finder.proto\x12\vuser_finder\x1a\x1bgoogle/protobuf/empty.proto\"*\n" +
	"\x12FindByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"8\n" +
	"\x0fSaveUserRequest\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.user_finder.UserR\x04user\"K\n" +
	"\fUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.user_finder.UserR\x04user\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"B\n" +
	"\x10SaveUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x89\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"slack_name\x18\x03 \x01(\tR\tslackName\x12\x19\n" +
	"\bslack_id\x18\x04 \x01(\tR\aslackId\x12!\n" +
	"\fgithub_login\x18\x05 \x01(\tR\vgithubLogin2\xf8\x01\n" +
	"\x11UserFinderService\x12I\n" +
	"\vFindByEmail\x12\x1f.user_finder.FindByEmailRequest\x1a\x19.user_finder.UserResponse\x12O\n" +
	"\x11FindByEmailWithDb\x12\x1f.user_finder.FindByEmailRequest\x1a\x19.user_finder.UserResponse\x12G\n" +
	"\bSaveUser\x12\x1c.user_finder.SaveUserRequest\x1a\x1d.user_finder.SaveUserResponseBFZDgithub.com/EktovVladimir/FordoTeamSlackBot/pkg/grpc/user_finder_grpcb\x06proto3"

var (
	file_proto_user_finder_user_finder_proto_rawDescOnce sync.Once
	file_proto_user_finder_user_finder_proto_rawDescData []byte
)

func file_proto_user_finder_user_finder_proto_rawDescGZIP() []byte {
	file_proto_user_finder_user_finder_proto_rawDescOnce.Do(func() {
		file_proto_user_finder_user_finder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_finder_user_finder_proto_rawDesc), len(file_proto_user_finder_user_finder_proto_rawDesc)))
	})
	return file_proto_user_finder_user_finder_proto_rawDescData
}

var file_proto_user_finder_user_finder_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_user_finder_user_finder_proto_goTypes = []any{
	(*FindByEmailRequest)(nil), // 0: user_finder.FindByEmailRequest
	(*SaveUserRequest)(nil),    // 1: user_finder.SaveUserRequest
	(*UserResponse)(nil),       // 2: user_finder.UserResponse
	(*SaveUserResponse)(nil),   // 3: user_finder.SaveUserResponse
	(*User)(nil),               // 4: user_finder.User
}
var file_proto_user_finder_user_finder_proto_depIdxs = []int32{
	4, // 0: user_finder.SaveUserRequest.user:type_name -> user_finder.User
	4, // 1: user_finder.UserResponse.user:type_name -> user_finder.User
	0, // 2: user_finder.UserFinderService.FindByEmail:input_type -> user_finder.FindByEmailRequest
	0, // 3: user_finder.UserFinderService.FindByEmailWithDb:input_type -> user_finder.FindByEmailRequest
	1, // 4: user_finder.UserFinderService.SaveUser:input_type -> user_finder.SaveUserRequest
	2, // 5: user_finder.UserFinderService.FindByEmail:output_type -> user_finder.UserResponse
	2, // 6: user_finder.UserFinderService.FindByEmailWithDb:output_type -> user_finder.UserResponse
	3, // 7: user_finder.UserFinderService.SaveUser:output_type -> user_finder.SaveUserResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_user_finder_user_finder_proto_init() }
func file_proto_user_finder_user_finder_proto_init() {
	if File_proto_user_finder_user_finder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_finder_user_finder_proto_rawDesc), len(file_proto_user_finder_user_finder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_finder_user_finder_proto_goTypes,
		DependencyIndexes: file_proto_user_finder_user_finder_proto_depIdxs,
		MessageInfos:      file_proto_user_finder_user_finder_proto_msgTypes,
	}.Build()
	File_proto_user_finder_user_finder_proto = out.File
	file_proto_user_finder_user_finder_proto_goTypes = nil
	file_proto_user_finder_user_finder_proto_depIdxs = nil
}
