// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/user_finder/user_finder.proto

package user_finder_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserFinderService_FindByEmail_FullMethodName       = "/user_finder.UserFinderService/FindByEmail"
	UserFinderService_FindByEmailWithDb_FullMethodName = "/user_finder.UserFinderService/FindByEmailWithDb"
	UserFinderService_SaveUser_FullMethodName          = "/user_finder.UserFinderService/SaveUser"
)

// UserFinderServiceClient is the client API for UserFinderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserFinderServiceClient interface {
	FindByEmail(ctx context.Context, in *FindByEmailRequest, opts ...grpc.CallOption) (*UserResponse, error)
	FindByEmailWithDb(ctx context.Context, in *FindByEmailRequest, opts ...grpc.CallOption) (*UserResponse, error)
	SaveUser(ctx context.Context, in *SaveUserRequest, opts ...grpc.CallOption) (*SaveUserResponse, error)
}

type userFinderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserFinderServiceClient(cc grpc.ClientConnInterface) UserFinderServiceClient {
	return &userFinderServiceClient{cc}
}

func (c *userFinderServiceClient) FindByEmail(ctx context.Context, in *FindByEmailRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, UserFinderService_FindByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userFinderServiceClient) FindByEmailWithDb(ctx context.Context, in *FindByEmailRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, UserFinderService_FindByEmailWithDb_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userFinderServiceClient) SaveUser(ctx context.Context, in *SaveUserRequest, opts ...grpc.CallOption) (*SaveUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveUserResponse)
	err := c.cc.Invoke(ctx, UserFinderService_SaveUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserFinderServiceServer is the server API for UserFinderService service.
// All implementations must embed UnimplementedUserFinderServiceServer
// for forward compatibility.
type UserFinderServiceServer interface {
	FindByEmail(context.Context, *FindByEmailRequest) (*UserResponse, error)
	FindByEmailWithDb(context.Context, *FindByEmailRequest) (*UserResponse, error)
	SaveUser(context.Context, *SaveUserRequest) (*SaveUserResponse, error)
	mustEmbedUnimplementedUserFinderServiceServer()
}

// UnimplementedUserFinderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserFinderServiceServer struct{}

func (UnimplementedUserFinderServiceServer) FindByEmail(context.Context, *FindByEmailRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByEmail not implemented")
}
func (UnimplementedUserFinderServiceServer) FindByEmailWithDb(context.Context, *FindByEmailRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByEmailWithDb not implemented")
}
func (UnimplementedUserFinderServiceServer) SaveUser(context.Context, *SaveUserRequest) (*SaveUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveUser not implemented")
}
func (UnimplementedUserFinderServiceServer) mustEmbedUnimplementedUserFinderServiceServer() {}
func (UnimplementedUserFinderServiceServer) testEmbeddedByValue()                           {}

// UnsafeUserFinderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserFinderServiceServer will
// result in compilation errors.
type UnsafeUserFinderServiceServer interface {
	mustEmbedUnimplementedUserFinderServiceServer()
}

func RegisterUserFinderServiceServer(s grpc.ServiceRegistrar, srv UserFinderServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserFinderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserFinderService_ServiceDesc, srv)
}

func _UserFinderService_FindByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFinderServiceServer).FindByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserFinderService_FindByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFinderServiceServer).FindByEmail(ctx, req.(*FindByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserFinderService_FindByEmailWithDb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFinderServiceServer).FindByEmailWithDb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserFinderService_FindByEmailWithDb_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFinderServiceServer).FindByEmailWithDb(ctx, req.(*FindByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserFinderService_SaveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFinderServiceServer).SaveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserFinderService_SaveUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFinderServiceServer).SaveUser(ctx, req.(*SaveUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserFinderService_ServiceDesc is the grpc.ServiceDesc for UserFinderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserFinderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_finder.UserFinderService",
	HandlerType: (*UserFinderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindByEmail",
			Handler:    _UserFinderService_FindByEmail_Handler,
		},
		{
			MethodName: "FindByEmailWithDb",
			Handler:    _UserFinderService_FindByEmailWithDb_Handler,
		},
		{
			MethodName: "SaveUser",
			Handler:    _UserFinderService_SaveUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user_finder/user_finder.proto",
}
