// Code generated by MockGen. DO NOT EDIT.
// Source: message_poster.go

// Package mock_slack_service is a generated GoMock package.
package mock_slack_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	slack "github.com/slack-go/slack"
)

// Mocksource is a mock of source interface.
type Mocksource struct {
	ctrl     *gomock.Controller
	recorder *MocksourceMockRecorder
}

// MocksourceMockRecorder is the mock recorder for Mocksource.
type MocksourceMockRecorder struct {
	mock *Mocksource
}

// NewMocksource creates a new mock instance.
func NewMocksource(ctrl *gomock.Controller) *Mocksource {
	mock := &Mocksource{ctrl: ctrl}
	mock.recorder = &MocksourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksource) EXPECT() *MocksourceMockRecorder {
	return m.recorder
}

// GetChannelId mocks base method.
func (m *Mocksource) GetChannelId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetChannelId indicates an expected call of GetChannelId.
func (mr *MocksourceMockRecorder) GetChannelId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelId", reflect.TypeOf((*Mocksource)(nil).GetChannelId))
}

// MocksourceWithUser is a mock of sourceWithUser interface.
type MocksourceWithUser struct {
	ctrl     *gomock.Controller
	recorder *MocksourceWithUserMockRecorder
}

// MocksourceWithUserMockRecorder is the mock recorder for MocksourceWithUser.
type MocksourceWithUserMockRecorder struct {
	mock *MocksourceWithUser
}

// NewMocksourceWithUser creates a new mock instance.
func NewMocksourceWithUser(ctrl *gomock.Controller) *MocksourceWithUser {
	mock := &MocksourceWithUser{ctrl: ctrl}
	mock.recorder = &MocksourceWithUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksourceWithUser) EXPECT() *MocksourceWithUserMockRecorder {
	return m.recorder
}

// GetUserId mocks base method.
func (m *MocksourceWithUser) GetUserId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserId indicates an expected call of GetUserId.
func (mr *MocksourceWithUserMockRecorder) GetUserId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserId", reflect.TypeOf((*MocksourceWithUser)(nil).GetUserId))
}

// MockslackClient is a mock of slackClient interface.
type MockslackClient struct {
	ctrl     *gomock.Controller
	recorder *MockslackClientMockRecorder
}

// MockslackClientMockRecorder is the mock recorder for MockslackClient.
type MockslackClientMockRecorder struct {
	mock *MockslackClient
}

// NewMockslackClient creates a new mock instance.
func NewMockslackClient(ctrl *gomock.Controller) *MockslackClient {
	mock := &MockslackClient{ctrl: ctrl}
	mock.recorder = &MockslackClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslackClient) EXPECT() *MockslackClientMockRecorder {
	return m.recorder
}

// DeleteMessageContext mocks base method.
func (m *MockslackClient) DeleteMessageContext(arg0 context.Context, arg1, arg2 string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessageContext", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteMessageContext indicates an expected call of DeleteMessageContext.
func (mr *MockslackClientMockRecorder) DeleteMessageContext(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessageContext", reflect.TypeOf((*MockslackClient)(nil).DeleteMessageContext), arg0, arg1, arg2)
}

// GetUserInfo mocks base method.
func (m *MockslackClient) GetUserInfo(arg0 string) (*slack.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", arg0)
	ret0, _ := ret[0].(*slack.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockslackClientMockRecorder) GetUserInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockslackClient)(nil).GetUserInfo), arg0)
}

// SendMessageContext mocks base method.
func (m *MockslackClient) SendMessageContext(arg0 context.Context, arg1 string, arg2 ...slack.MsgOption) (string, string, string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendMessageContext", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// SendMessageContext indicates an expected call of SendMessageContext.
func (mr *MockslackClientMockRecorder) SendMessageContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageContext", reflect.TypeOf((*MockslackClient)(nil).SendMessageContext), varargs...)
}
