// Code generated by MockGen. DO NOT EDIT.
// Source: message_poster.go

// Package mock_slack_service is a generated GoMock package.
package mock_slack_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	slack "github.com/slack-go/slack"
)

// Mocksource is a mock of source interface.
type Mocksource struct {
	ctrl     *gomock.Controller
	recorder *MocksourceMockRecorder
}

// MocksourceMockRecorder is the mock recorder for Mocksource.
type MocksourceMockRecorder struct {
	mock *Mocksource
}

// NewMocksource creates a new mock instance.
func NewMocksource(ctrl *gomock.Controller) *Mocksource {
	mock := &Mocksource{ctrl: ctrl}
	mock.recorder = &MocksourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksource) EXPECT() *MocksourceMockRecorder {
	return m.recorder
}

// GetChannelId mocks base method.
func (m *Mocksource) GetChannelId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetChannelId indicates an expected call of GetChannelId.
func (mr *MocksourceMockRecorder) GetChannelId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelId", reflect.TypeOf((*Mocksource)(nil).GetChannelId))
}

// MockslackClient is a mock of slackClient interface.
type MockslackClient struct {
	ctrl     *gomock.Controller
	recorder *MockslackClientMockRecorder
}

// MockslackClientMockRecorder is the mock recorder for MockslackClient.
type MockslackClientMockRecorder struct {
	mock *MockslackClient
}

// NewMockslackClient creates a new mock instance.
func NewMockslackClient(ctrl *gomock.Controller) *MockslackClient {
	mock := &MockslackClient{ctrl: ctrl}
	mock.recorder = &MockslackClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslackClient) EXPECT() *MockslackClientMockRecorder {
	return m.recorder
}

// SendMessageContext mocks base method.
func (m *MockslackClient) SendMessageContext(arg0 context.Context, arg1 string, arg2 ...slack.MsgOption) (string, string, string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendMessageContext", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// SendMessageContext indicates an expected call of SendMessageContext.
func (mr *MockslackClientMockRecorder) SendMessageContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageContext", reflect.TypeOf((*MockslackClient)(nil).SendMessageContext), varargs...)
}
