// Code generated by MockGen. DO NOT EDIT.
// Source: user_finder.go

// Package mock_user_finder is a generated GoMock package.
package mock_user_finder

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	github "github.com/google/go-github/v72/github"
	slack "github.com/slack-go/slack"
)

// MockslackClient is a mock of slackClient interface.
type MockslackClient struct {
	ctrl     *gomock.Controller
	recorder *MockslackClientMockRecorder
}

// MockslackClientMockRecorder is the mock recorder for MockslackClient.
type MockslackClientMockRecorder struct {
	mock *MockslackClient
}

// NewMockslackClient creates a new mock instance.
func NewMockslackClient(ctrl *gomock.Controller) *MockslackClient {
	mock := &MockslackClient{ctrl: ctrl}
	mock.recorder = &MockslackClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslackClient) EXPECT() *MockslackClientMockRecorder {
	return m.recorder
}

// GetUserByEmailContext mocks base method.
func (m *MockslackClient) GetUserByEmailContext(arg0 context.Context, arg1 string) (*slack.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmailContext", arg0, arg1)
	ret0, _ := ret[0].(*slack.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmailContext indicates an expected call of GetUserByEmailContext.
func (mr *MockslackClientMockRecorder) GetUserByEmailContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmailContext", reflect.TypeOf((*MockslackClient)(nil).GetUserByEmailContext), arg0, arg1)
}

// MockgithubSearchService is a mock of githubSearchService interface.
type MockgithubSearchService struct {
	ctrl     *gomock.Controller
	recorder *MockgithubSearchServiceMockRecorder
}

// MockgithubSearchServiceMockRecorder is the mock recorder for MockgithubSearchService.
type MockgithubSearchServiceMockRecorder struct {
	mock *MockgithubSearchService
}

// NewMockgithubSearchService creates a new mock instance.
func NewMockgithubSearchService(ctrl *gomock.Controller) *MockgithubSearchService {
	mock := &MockgithubSearchService{ctrl: ctrl}
	mock.recorder = &MockgithubSearchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgithubSearchService) EXPECT() *MockgithubSearchServiceMockRecorder {
	return m.recorder
}

// Users mocks base method.
func (m *MockgithubSearchService) Users(arg0 context.Context, arg1 string, arg2 *github.SearchOptions) (*github.UsersSearchResult, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Users", arg0, arg1, arg2)
	ret0, _ := ret[0].(*github.UsersSearchResult)
	ret1, _ := ret[1].(*github.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Users indicates an expected call of Users.
func (mr *MockgithubSearchServiceMockRecorder) Users(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Users", reflect.TypeOf((*MockgithubSearchService)(nil).Users), arg0, arg1, arg2)
}
