// Code generated by MockGen. DO NOT EDIT.
// Source: gh_service.go

// Package mock_gh_service is a generated GoMock package.
package mock_gh_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	github "github.com/google/go-github/v72/github"
	context "golang.org/x/net/context"
)

// MockgithubPullRequestService is a mock of githubPullRequestService interface.
type MockgithubPullRequestService struct {
	ctrl     *gomock.Controller
	recorder *MockgithubPullRequestServiceMockRecorder
}

// MockgithubPullRequestServiceMockRecorder is the mock recorder for MockgithubPullRequestService.
type MockgithubPullRequestServiceMockRecorder struct {
	mock *MockgithubPullRequestService
}

// NewMockgithubPullRequestService creates a new mock instance.
func NewMockgithubPullRequestService(ctrl *gomock.Controller) *MockgithubPullRequestService {
	mock := &MockgithubPullRequestService{ctrl: ctrl}
	mock.recorder = &MockgithubPullRequestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgithubPullRequestService) EXPECT() *MockgithubPullRequestServiceMockRecorder {
	return m.recorder
}

// ListCommits mocks base method.
func (m *MockgithubPullRequestService) ListCommits(arg0 context.Context, arg1, arg2 string, arg3 int, arg4 *github.ListOptions) ([]*github.RepositoryCommit, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCommits", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*github.RepositoryCommit)
	ret1, _ := ret[1].(*github.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCommits indicates an expected call of ListCommits.
func (mr *MockgithubPullRequestServiceMockRecorder) ListCommits(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommits", reflect.TypeOf((*MockgithubPullRequestService)(nil).ListCommits), arg0, arg1, arg2, arg3, arg4)
}

// ListReviewers mocks base method.
func (m *MockgithubPullRequestService) ListReviewers(arg0 context.Context, arg1, arg2 string, arg3 int, arg4 *github.ListOptions) (*github.Reviewers, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReviewers", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*github.Reviewers)
	ret1, _ := ret[1].(*github.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListReviewers indicates an expected call of ListReviewers.
func (mr *MockgithubPullRequestServiceMockRecorder) ListReviewers(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReviewers", reflect.TypeOf((*MockgithubPullRequestService)(nil).ListReviewers), arg0, arg1, arg2, arg3, arg4)
}
